# Generated by Django 2.0.5 on 2018-11-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.CharField(max_length=200)),
                ('credit', models.CharField(max_length=200, verbose_name='to account')),
                ('dollars', models.PositiveIntegerField()),
                ('memo', models.CharField(max_length=200)),
            ],
        ),
    ]
